# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published
# by the Free Software Foundation.#
#
# Copyright (C) 2016 Realtek Semiconductor Corp.
# Author: Phinex Hung <phinexhung@realtek.com>


obj-y := init.o irq.o timer.o
obj-$(CONFIG_RTL8117_EHCI) += rtl8117-ehci.o rtl8117-ehci-core.o rtl8117-ehci-device.o
obj-$(CONFIG_RTL8117_CMAC) += rtl8117-cmac.o
