
ccflags-$(CONFIG_RTK_RPC) += -Idrivers/soc/realtek/include
ccflags-$(CONFIG_RTK_RPC) += -Idrivers/soc/realtek/rtd119x
ccflags-$(CONFIG_RTK_RPC) += -Idrivers/soc/realtek/rtd119x/include

obj-$(CONFIG_RTK_RPC) += RPCDriver.o
obj-$(CONFIG_RTK_RPC) += RPCintr.o
obj-$(CONFIG_RTK_RPC) += RPCpoll.o
obj-$(CONFIG_RTK_RPC) += RPCkern.o

