#!/bin/sh
#
# Copyright (C) 2011-2012 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

ubootenv_add_uci_config "/dev/mtd0" "0x0" "0x10000" "0x10000"
config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
