obj-$(CONFIG_ARCH_RTD119X)		+= rtd119x_restart.o
obj-$(CONFIG_HOTPLUG_CPU)		+= rtd119x_hotplug.o
obj-$(CONFIG_RTK_RBUS_BARRIER)		+= rtd119x_barrier.o
obj-$(CONFIG_RTK_MEM_REMAP)		+= rtd119x_memory_remap.o
obj-$(CONFIG_RTK_SB2_MEM_TRASH_MONITOR) += rtd119x_sb2_dbg.o
obj-$(CONFIG_RTK_RPC)			+= rpc/
obj-$(CONFIG_SUSPEND)			+= rtd119x_suspend.o rtd119x_resume.o rtd119x_ip_power.o