dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-qa-rescue.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-1GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-2GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-4GB.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-1GB-MM.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-2GB-MM.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-2GB-MM.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-4GB-MM.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-2GB-HDMI.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1296-saola-4GB-HDMI.dtb
dtb-$(CONFIG_ARCH_RTD129X) += rtd-1295-giraffe-2GB-HDMI.dtb


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
