#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Wake Up Host through Proc for RTL8117
LUCI_DEPENDS:= @TARGET_rtl8117

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
